package servlet101;

import java.io.IOException;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class Testservlet
 */
@WebServlet("/Testservlet")
public class Testservlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

    /**
     * Default constructor. 
     */

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
response.setContentType("text/html");
response.getWriter().println("<!DOCTYPE html>\r\n"
		+ "<html lang=\"en\">\r\n"
		+ "\r\n"
		+ "<head>\r\n"
		+ "    <meta charset=\"UTF-8\" />\r\n"
		+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n"
		+ "    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css\"\r\n"
		+ "        integrity=\"sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==\"\r\n"
		+ "        crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n"
		+ "    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css\"\r\n"
		+ "        integrity=\"sha512-NhSC1YmyruXifcj/KFRWoC561YpHpc5Jtzgvbuzx5VozKpWvQ+4nXhPdFgmx8xqexRcpAglTj9sIBWINXa8x5w==\"\r\n"
		+ "        crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n"
		+ "\r\n"
		+ "    <link rel=\"stylesheet\" href=\"/HelloWorld/TheBand/assest/css/style.css\" />\r\n"
		+ "    <!-- <link rel=\"stylesheet\" href=\"/HelloWorld/TheBand/assest/css/theband.css\"> -->\r\n"
		+ "    <link rel=\"stylesheet\" href=\"/HelloWorld/TheBand/assest/css/base.css\" />\r\n"
		+ "    <link rel=\"stylesheet\" href=\"/HelloWorld/TheBand/assest/font/font.css\" />\r\n"
		+ "    <title>TEST</title>\r\n"
		+ "    <link rel=\"apple-touch-icon\" sizes=\"180x180\"\r\n"
		+ "        href=\"/HelloWorld/TheBand/assest/img/favicon_io/apple-touch-icon.png\" />\r\n"
		+ "    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\"\r\n"
		+ "        href=\"/HelloWorld/TheBand/assest/img/favicon_io/favicon-32x32.png\" />\r\n"
		+ "    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\"\r\n"
		+ "        href=\"/HelloWorld/TheBand/assest/img/favicon_io/favicon-16x16.png\" />\r\n"
		+ "    <link rel=\"manifest\" href=\"/HelloWorld/TheBand/assest/img/favicon_io/site.webmanifest\" />\r\n"
		+ "</head>\r\n"
		+ "\r\n"
		+ "<body id=\"top\" class=\"w-full\">\r\n"
		+ "    <!-- <div class=\"header flex bg-black w-full fixed items-center z-20 top-0 justify-between sm:justify-start\" id=\"\">\r\n"
		+ "        <a href=\"\"\r\n"
		+ "            class=\"header__link text-white bg-black flex items-center h-12 max-w-32 py-3 px-6 hover:bg-hover-bg hover:text-black\">HOME</a>\r\n"
		+ "        <a href=\"#band\"\r\n"
		+ "            class=\"header__link text-white bg-black hidden items-center h-12 max-w-32 py-3 px-6 hover:bg-hover-bg hover:text-black sm:flex\">BAND</a>\r\n"
		+ "        <a href=\"#tour\"\r\n"
		+ "            class=\"header__link text-white bg-black hidden items-center h-12 max-w-32 py-3 px-6 hover:bg-hover-bg hover:text-black sm:flex\">TOUR</a>\r\n"
		+ "        <a href=\"#contact\"\r\n"
		+ "            class=\"header__link text-white bg-black hidden items-center h-12 max-w-32 py-3 px-6 hover:bg-hover-bg hover:text-black sm:flex\">CONTACT</a>\r\n"
		+ "\r\n"
		+ "            <div class=\"no-style2 relative group flex sm:hidden\">\r\n"
		+ "                <button title=\"MORE\"\r\n"
		+ "                    class=\"header__navbar-more text-white bg-black flex items-center h-12 max-w-32 py-3 px-6 group-hover:text-black group-hover:bg-hover-bg\">\r\n"
		+ "                    <i class=\"fa-solid fa-list text-2xl\"></i>\r\n"
		+ "                </button>\r\n"
		+ "                <div\r\n"
		+ "                    class=\"header__navbar-more-drop-down-menu hidden absolute right-0 top-12 bg-white text-black w-fullriel group-hover:block shadow-custom\">\r\n"
		+ "                    <a href=\"#band\"\r\n"
		+ "                        class=\"header__link text-white bg-black flex flex-1 items-center h-12 py-3 px-6 hover:bg-hover-bg hover:text-black\">BAND</a>\r\n"
		+ "                    <a href=\"#tour\"\r\n"
		+ "                        class=\"header__link text-white bg-black flex flex-1 items-center h-12 py-3 px-6 hover:bg-hover-bg hover:text-black\">TOUR</a>\r\n"
		+ "                    <a href=\"#contact\"\r\n"
		+ "                        class=\"header__link text-white bg-black flex flex-1 items-center h-12 py-3 px-6 hover:bg-hover-bg hover:text-black\">CONTACT</a>\r\n"
		+ "                </div>\r\n"
		+ "            </div>\r\n"
		+ "\r\n"
		+ "\r\n"
		+ "<div class=\"no-style relative group hidden sm:flex\">\r\n"
		+ "    <button title=\"MORE\"\r\n"
		+ "        class=\"header__navbar-more text-white bg-black flex items-center h-12 max-w-32 py-3 px-6 group-hover:text-black group-hover:bg-hover-bg\">\r\n"
		+ "        MORE\r\n"
		+ "        <i class=\"fa-solid fa-caret-down\"></i>\r\n"
		+ "    </button>\r\n"
		+ "    <div\r\n"
		+ "        class=\"header__navbar-more-drop-down-menu hidden absolute left-0 top-12 bg-white text-black min-w-44 group-hover:block shadow-custom\">\r\n"
		+ "        <a href=\"\"\r\n"
		+ "            class=\"header__drop-down-link text-black flex items-center w-full px-6 py-2 hover:bg-hover-bg\">Merch</a>\r\n"
		+ "        <a href=\"\"\r\n"
		+ "            class=\"header__drop-down-link text-black flex items-center w-full px-6 py-2 hover:bg-hover-bg\">Extras</a>\r\n"
		+ "        <a href=\"\"\r\n"
		+ "            class=\"header__drop-down-link text-black flex items-center w-full px-6 py-2 hover:bg-hover-bg\">Media</a>\r\n"
		+ "    </div>\r\n"
		+ "</div>\r\n"
		+ "\r\n"
		+ "\r\n"
		+ "        <div class=\"header__navbar-search hidden items-center text-white px-6 py-3 h-12 ml-auto hover:bg-red-600 sm:flex\">\r\n"
		+ "            <i class=\"fa-solid fa-magnifying-glass\"></i>\r\n"
		+ "        </div>\r\n"
		+ "    </div> -->\r\n"
		+ "\r\n"
		+ "    <!-- new -->\r\n"
		+ "    <div class=\"header flex bg-black w-full fixed items-center z-20 top-0 justify-between sm:justify-start\" id=\"\">\r\n"
		+ "        <a href=\"\"\r\n"
		+ "            class=\"header__link text-white bg-black flex items-center h-12 max-w-32 py-3 px-6 hover:bg-hover-bg hover:text-black\">HOME</a>\r\n"
		+ "        <a href=\"#band\"\r\n"
		+ "            class=\"header__link text-white bg-black hidden items-center h-12 max-w-32 py-3 px-6 hover:bg-hover-bg hover:text-black sm:flex\">BAND</a>\r\n"
		+ "        <a href=\"/HelloWorld/Testservlet\"\r\n"
		+ "            class=\"header__link text-white bg-black hidden items-center h-12 max-w-32 py-3 px-6 hover:bg-hover-bg hover:text-black sm:flex\">TOUR</a>\r\n"
		+ "        <a href=\"#contact\"\r\n"
		+ "            class=\"header__link text-white bg-black hidden items-center h-12 max-w-32 py-3 px-6 hover:bg-hover-bg hover:text-black sm:flex\">CONTACT</a>\r\n"
		+ "\r\n"
		+ "        <!-- normal -->\r\n"
		+ "        <div class=\"no-style relative group hidden sm:flex\">\r\n"
		+ "            <button title=\"MORE\"\r\n"
		+ "                class=\"header__navbar-more text-white bg-black flex items-center h-12 max-w-32 py-3 px-6 group-hover:text-black group-hover:bg-hover-bg\">\r\n"
		+ "                MORE\r\n"
		+ "                <i class=\"fa-solid fa-caret-down\"></i>\r\n"
		+ "            </button>\r\n"
		+ "            <div\r\n"
		+ "                class=\"header__navbar-more-drop-down-menu hidden absolute left-0 top-12 bg-white text-black min-w-44 group-hover:block shadow-custom\">\r\n"
		+ "                <a href=\"\"\r\n"
		+ "                    class=\"header__drop-down-link text-black flex items-center w-full px-6 py-2 hover:bg-hover-bg\">Merch</a>\r\n"
		+ "                <a href=\"\"\r\n"
		+ "                    class=\"header__drop-down-link text-black flex items-center w-full px-6 py-2 hover:bg-hover-bg\">Extras</a>\r\n"
		+ "                <a href=\"\"\r\n"
		+ "                    class=\"header__drop-down-link text-black flex items-center w-full px-6 py-2 hover:bg-hover-bg\">Media</a>\r\n"
		+ "            </div>\r\n"
		+ "        </div>\r\n"
		+ "        <!-- normal -->\r\n"
		+ "\r\n"
		+ "        <div\r\n"
		+ "            class=\"header__navbar-search hidden items-center text-white px-6 py-3 h-12 ml-auto hover:bg-red-600 sm:flex\">\r\n"
		+ "            <i class=\"fa-solid fa-magnifying-glass\"></i>\r\n"
		+ "        </div>\r\n"
		+ "    </div>\r\n"
		+ "\r\n"
		+ "    <div class=\"no-style2 fixed top-0 w-full h-12 flex sm:hidden z-20 bg-transparent\">\r\n"
		+ "        <button title=\"MORE\"\r\n"
		+ "            class=\"header__navbar-more text-white bg-black flex items-center h-12 max-w-32 py-3 px-6 ml-auto hover:text-black hover:bg-hover-bg \"\r\n"
		+ "            onclick=\"Dropdown();\">\r\n"
		+ "            <i class=\"fa-solid fa-list text-2xl\"></i>\r\n"
		+ "        </button>\r\n"
		+ "        <div id=\"drop-down-menu\"\r\n"
		+ "            class=\"header__navbar-more-drop-down-menu hidden flex-col absolute right-0 top-12 bg-white text-black w-full shadow-custom\">\r\n"
		+ "            <a href=\"#band\"\r\n"
		+ "                class=\"header__link text-white bg-black flex flex-1 items-center h-12 py-3 px-6 hover:bg-hover-bg hover:text-black\">BAND</a>\r\n"
		+ "            <a href=\"#tour\"\r\n"
		+ "                class=\"header__link text-white bg-black flex flex-1 items-center h-12 py-3 px-6 hover:bg-hover-bg hover:text-black\">TOUR</a>\r\n"
		+ "            <a href=\"#contact\"\r\n"
		+ "                class=\"header__link text-white bg-black flex flex-1 items-center h-12 py-3 px-6 hover:bg-hover-bg hover:text-black\">CONTACT</a>\r\n"
		+ "        </div>\r\n"
		+ "    </div>\r\n"
		+ "\r\n"
		+ "\r\n"
		+ "\r\n"
		+ "\r\n"
		+ "\r\n"
		+ "    <!-- new -->\r\n"
		+ "    <div class=\"content w-full p-0 lazy-load\">\r\n"
		+ "        <div class=\"cover__image slide-img w-full z-10 relative mt-12\" id=\"top\">\r\n"
		+ "            <img src=\"/HelloWorld/TheBand/assest/img/chicago.jpg\" alt=\"cover\" class=\"cover__image-img block w-full\" />\r\n"
		+ "            <div class=\"cover__image-text absolute bottom-0 text-center left-1/2 text-white -translate-x-1/2 py-9 px-4\">\r\n"
		+ "                <h3 class=\"cover__image-text-title my-2.5\">THE BAND</h3>\r\n"
		+ "                <p class=\"my-4\">\r\n"
		+ "                    <b>Hello the world this sunday night</b>\r\n"
		+ "                </p>\r\n"
		+ "            </div>\r\n"
		+ "        </div>\r\n"
		+ "        <div class=\"cover__image slide-img w-full z-10 relative mt-12\" id=\"top\">\r\n"
		+ "            <img src=\"/HelloWorld/TheBand/assest/img/la.jpg\" alt=\"cover\" class=\"cover__image-img w-full\" />\r\n"
		+ "            <div class=\"cover__image-text absolute bottom-0 text-center left-1/2 text-white -translate-x-1/2 py-9 px-4\">\r\n"
		+ "                <h3 class=\"cover__image-text-title my-2.5 text-black sm:text-white\">THE BAND</h3>\r\n"
		+ "                <p class=\"my-4\">\r\n"
		+ "                    <b>Hello the world this sunday night</b>\r\n"
		+ "                </p>\r\n"
		+ "            </div>\r\n"
		+ "        </div>\r\n"
		+ "        <div class=\"cover__image slide-img w-full z-10 relative mt-12\" id=\"top\">\r\n"
		+ "            <img src=\"/HelloWorld/TheBand/assest/img/ny.jpg\" alt=\"cover\" class=\"cover__image-img block w-full\" />\r\n"
		+ "            <div class=\"cover__image-text absolute bottom-0 text-center left-1/2 text-white -translate-x-1/2 py-9 px-4\">\r\n"
		+ "                <h3 class=\"cover__image-text-title my-2.5\">THE BAND</h3>\r\n"
		+ "                <p class=\"my-4\">\r\n"
		+ "                    <b>Hello the world this sunday night</b>\r\n"
		+ "                </p>\r\n"
		+ "            </div>\r\n"
		+ "        </div>\r\n"
		+ "\r\n"
		+ "        <div class=\"content-intro flex flex-col justify-center items-center max-w-3xl w-full ml-auto mr-auto py-16 px-4 lazy-load\"\r\n"
		+ "            id=\"band\">\r\n"
		+ "            <h1 class=\"intro-title tracking-widest w-full text-center\">The Band</h1>\r\n"
		+ "            <p class=\"intro-title-small-print text-base italic opacity-80 my-2.5 w-full text-center\">\r\n"
		+ "                We love music\r\n"
		+ "            </p>\r\n"
		+ "            <p class=\"intro-paragraph my-2.5 w-full\">\r\n"
		+ "                We have created a fictional band website. Lorem ipsum dolor sit amet,\r\n"
		+ "                consectetur adipiscing elit, sed do eiusmod tempor incididunt ut\r\n"
		+ "                labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud\r\n"
		+ "                exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\r\n"
		+ "                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum\r\n"
		+ "                dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n"
		+ "                proident, sunt in culpa qui officia deserunt mollit anim id est\r\n"
		+ "                laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt\r\n"
		+ "                ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis\r\n"
		+ "                nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n"
		+ "                consequat. Duis aute irure dolor in reprehenderit in voluptate\r\n"
		+ "            </p>\r\n"
		+ "            <div class=\"intro-members flex justify-center items-center w-full py-16 px-4 flex-col sm:flex-row lazy-load\">\r\n"
		+ "                <div class=\"members flex justify-center items-center flex-col w-full object-contain\">\r\n"
		+ "                    <p class=\"members__name my-2.5 opacity-80 text-base\">Name</p>\r\n"
		+ "                    <img src=\"/HelloWorld/TheBand/assest/img/bandmember.jpg\" alt=\"bandmember\"\r\n"
		+ "                        class=\"members__img w-3/5\" />\r\n"
		+ "                </div>\r\n"
		+ "                <div class=\"members flex justify-center items-center flex-col w-full object-contain\">\r\n"
		+ "                    <p class=\"members__name my-2.5 opacity-80 text-base\">Name</p>\r\n"
		+ "                    <img src=\"/HelloWorld/TheBand/assest/img/bandmember.jpg\" alt=\"bandmember\"\r\n"
		+ "                        class=\"members__img w-3/5\" />\r\n"
		+ "                </div>\r\n"
		+ "                <div class=\"members flex justify-center items-center flex-col w-full object-contain\">\r\n"
		+ "                    <p class=\"members__name my-2.5 opacity-80 text-base\">Name</p>\r\n"
		+ "                    <img src=\"/HelloWorld/TheBand/assest/img/bandmember.jpg\" alt=\"bandmember\"\r\n"
		+ "                        class=\"members__img w-3/5\" />\r\n"
		+ "                </div>\r\n"
		+ "            </div>\r\n"
		+ "        </div>\r\n"
		+ "\r\n"
		+ "        <div class=\"content-body text-white bg-black lazy-load\">\r\n"
		+ "            <div class=\"content-body-container flex flex-col justify-center items-center max-w-3xl w-full ml-auto mr-auto py-16 px-4\"\r\n"
		+ "                id=\"tour\">\r\n"
		+ "                <h1 class=\"intro-title tracking-widest w-full text-center\">TOUR</h1>\r\n"
		+ "                <p class=\"intro-title-small-print text-base italic opacity-80 my-2.5 w-full text-center\">\r\n"
		+ "                    Remember to book our ticket!\r\n"
		+ "                </p>\r\n"
		+ "                <ul class=\"ticket-list flex flex-col w-full bg-white list-none pl-0\">\r\n"
		+ "                    <li\r\n"
		+ "                        class=\"ticket-list-item flex text-text-2 items-center border-b border-border-color py-2.5 px-1.5 flex-1\">\r\n"
		+ "                        September\r\n"
		+ "                        <span class=\"ticket-sold-out bg-red-500 text-white ml-4 px-2\">Sold out</span>\r\n"
		+ "                    </li>\r\n"
		+ "                    <li\r\n"
		+ "                        class=\"ticket-list-item flex text-text-2 items-center border-b border-border-color py-2.5 px-1.5 flex-1\">\r\n"
		+ "                        October\r\n"
		+ "                        <span class=\"ticket-sold-out bg-red-500 text-white ml-4 px-2\">Sold out</span>\r\n"
		+ "                    </li>\r\n"
		+ "                    <li\r\n"
		+ "                        class=\"ticket-list-item flex text-text-2 items-center border-b border-border-color py-2.5 px-1.5 flex-1\">\r\n"
		+ "                        November\r\n"
		+ "                        <!-- <span class=\"ticket-sold-out\">Sold out</span> -->\r\n"
		+ "                        <span\r\n"
		+ "                            class=\"ticket-left flex bg-black w-7 h-6 text-white justify-center items-center rounded-3xl ml-auto mr-7\">3</span>\r\n"
		+ "                    </li>\r\n"
		+ "                </ul>\r\n"
		+ "\r\n"
		+ "                <div class=\"tour__destination flex py-8 px-2 bg-transparent -mx-4 items-center flex-col sm:flex-row lazy-load\">\r\n"
		+ "                    <div class=\"destination flex bg-black text-black w-full sm:w-1/3 px-2 flex-col pt-4 sm:pt-0\">\r\n"
		+ "                        <img src=\"/HelloWorld/TheBand/assest/img/newyork.jpg\" alt=\"\"\r\n"
		+ "                            class=\"destination-img object-cover w-full hover:opacity-80\" />\r\n"
		+ "                        <div class=\"destination-info bg-white text-black px-4\">\r\n"
		+ "                            <p class=\"destination-name my-4\">\r\n"
		+ "                                <b> New York </b>\r\n"
		+ "                            </p>\r\n"
		+ "                            <p class=\"time my-4\">Fri 27 Nov 2016</p>\r\n"
		+ "                            <p class=\"destination-detail line-clamp-2 overflow-hidden my-4\">\r\n"
		+ "                                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt\r\n"
		+ "                                ratione harum corporis voluptas, quos quibusdam, perferendis\r\n"
		+ "                                quaerat necessitatibus voluptate adipisci quia, tenetur earum\r\n"
		+ "                                assumenda numquam ab ullam rem omnis consectetur.\r\n"
		+ "                            </p>\r\n"
		+ "                            <button\r\n"
		+ "                                class=\"buy-ticket-btn mb-4 outline-none border-none bg-black py-2 px-4 text-white hover:bg-hover-bg hover:text-black hover:cursor-pointer\"\r\n"
		+ "                                onclick=\"openModal();\">\r\n"
		+ "                                Buy Tickets\r\n"
		+ "                            </button>\r\n"
		+ "                        </div>\r\n"
		+ "                    </div>\r\n"
		+ "\r\n"
		+ "                    <div class=\"destination flex bg-black text-black w-full sm:w-1/3 px-2 flex-col pt-4 sm:pt-0 lazy-load\">\r\n"
		+ "                        <img src=\"/HelloWorld/TheBand/assest/img/paris.jpg\" alt=\"\"\r\n"
		+ "                            class=\"destination-img object-cover w-full hover:opacity-80\" />\r\n"
		+ "                        <div class=\"destination-info bg-white text-black px-4\">\r\n"
		+ "                            <p class=\"destination-name my-4\">\r\n"
		+ "                                <b> Paris </b>\r\n"
		+ "                            </p>\r\n"
		+ "                            <p class=\"time my-4\">Fri 27 Nov 2016</p>\r\n"
		+ "                            <p class=\"destination-detail line-clamp-2 overflow-hidden my-4\">\r\n"
		+ "                                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt\r\n"
		+ "                                ratione harum corporis voluptas, quos quibusdam, perferendis\r\n"
		+ "                                quaerat necessitatibus voluptate adipisci quia, tenetur earum\r\n"
		+ "                                assumenda numquam ab ullam rem omnis consectetur.\r\n"
		+ "                            </p>\r\n"
		+ "                            <button\r\n"
		+ "                                class=\"buy-ticket-btn mb-4 outline-none border-none bg-black py-2 px-4 text-white hover:bg-hover-bg hover:text-black hover:cursor-pointer\"\r\n"
		+ "                                onclick=\"openModal();\">\r\n"
		+ "                                Buy Tickets\r\n"
		+ "                            </button>\r\n"
		+ "                        </div>\r\n"
		+ "                    </div>\r\n"
		+ "\r\n"
		+ "                    <div class=\"destination flex bg-black text-black w-full sm:w-1/3 px-2 flex-col pt-4 sm:pt-0 lazy-load\">\r\n"
		+ "                        <img src=\"/HelloWorld/TheBand/assest/img/sanfran.jpg\" alt=\"\"\r\n"
		+ "                            class=\"destination-img object-cover w-full hover:opacity-80\" />\r\n"
		+ "                        <div class=\"destination-info bg-white text-black px-4\">\r\n"
		+ "                            <p class=\"destination-name my-4\">\r\n"
		+ "                                <b> San Francisco </b>\r\n"
		+ "                            </p>\r\n"
		+ "                            <p class=\"time my-4\">Fri 27 Nov 2016</p>\r\n"
		+ "                            <p class=\"destination-detail line-clamp-2 overflow-hidden my-4\">\r\n"
		+ "                                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt\r\n"
		+ "                                ratione harum corporis voluptas, quos quibusdam, perferendis\r\n"
		+ "                                quaerat necessitatibus voluptate adipisci quia, tenetur earum\r\n"
		+ "                                assumenda numquam ab ullam rem omnis consectetur.\r\n"
		+ "                            </p>\r\n"
		+ "                            <button\r\n"
		+ "                                class=\"buy-ticket-btn mb-4 outline-none border-none bg-black py-2 px-4 text-white hover:bg-hover-bg hover:text-black hover:cursor-pointer\"\r\n"
		+ "                                onclick=\"openModal();\">\r\n"
		+ "                                Buy Tickets\r\n"
		+ "                            </button>\r\n"
		+ "                        </div>\r\n"
		+ "                    </div>\r\n"
		+ "                </div>\r\n"
		+ "            </div>\r\n"
		+ "        </div>\r\n"
		+ "        <div class=\"contact flex items-center max-w-3xl w-full ml-auto mr-auto justify-center py-16 px-4\" id=\"contact\">\r\n"
		+ "            <div class=\"contact-container flex items-center justify-center flex-col flex-1\">\r\n"
		+ "                <h1 class=\"intro-title tracking-widest w-full text-center\">\r\n"
		+ "                    CONTACT\r\n"
		+ "                </h1>\r\n"
		+ "                <p class=\"intro-title-small-print text-base italic opacity-80 my-2.5 w-full text-center\"\r\n"
		+ "                    style=\"margin-bottom: 16px\">\r\n"
		+ "                    Fan? Drop a note!\r\n"
		+ "                </p>\r\n"
		+ "                <div class=\"contact-info-conatainer flex w-full flex-col sm:flex-row pt-8 pb-4 items-center\">\r\n"
		+ "                    <address class=\"column1 w-full sm:w-1/2\">\r\n"
		+ "                        <div class=\"contact-info flex flex-row items-center\">\r\n"
		+ "                            <i class=\"fa fa-map-marker\" style=\"padding-right: 2px; margin-left: 2px\"></i>\r\n"
		+ "                            <p class=\"contact-info-text ml-2.5\">Chicago, US</p>\r\n"
		+ "                        </div>\r\n"
		+ "                        <div class=\"contact-info flex flex-row items-center\">\r\n"
		+ "                            <i class=\"fa fa-phone\"></i>\r\n"
		+ "                            <p class=\"contact-info-text ml-2.5\">Phone:+00 151515</p>\r\n"
		+ "                        </div>\r\n"
		+ "                        <div class=\"contact-info flex flex-row items-center\">\r\n"
		+ "                            <i class=\"fa fa-envelope\"></i>\r\n"
		+ "                            <p class=\"contact-info-text ml-2.5\">Email: mail@mail.com</p>\r\n"
		+ "                        </div>\r\n"
		+ "                    </address>\r\n"
		+ "                    <div class=\"column2 w-full sm:w-1/2\" autocomplete=\"on\">\r\n"
		+ "                        <div class=\"contact-form w-full flex flex-col\">\r\n"
		+ "                            <div class=\"contact-form-input flex flex-col sm:flex-row sm:justify-center\" autocomplete=\"on\">\r\n"
		+ "                                <div class=\"sm:pr-2\">\r\n"
		+ "                                    <input type=\"text\" placeholder=\"Name\" id=\"name\"\r\n"
		+ "                                        class=\"contact-form-input-name w-full sm:w-full outline-black p-2 border border-border-color mt-2.5 sm:mt-0\"\r\n"
		+ "                                        required name=\"Name\" autocomplete=\"on\"/>\r\n"
		+ "                                </div>\r\n"
		+ "                                <div class=\"sm:pl-2\">\r\n"
		+ "                                    <input type=\"email\" placeholder=\"Email\" id=\"email\"\r\n"
		+ "                                        class=\"contact-form-input-email w-full sm:w-full outline-black p-2 border border-border-color mt-2.5 sm:mt-0\"\r\n"
		+ "                                        required name=\"Email\" autocomplete=\"on\"/>\r\n"
		+ "                                </div>\r\n"
		+ "                            </div>\r\n"
		+ "                            <div class=\"contact-form-input-2 mt-2.5\">\r\n"
		+ "                                <input type=\"text\" placeholder=\"Message\" required name=\"Message\" id=\"message\"\r\n"
		+ "                                    class=\"contact-form-input-message w-full outline-black p-2 border border-border-color\" />\r\n"
		+ "                            </div>\r\n"
		+ "                        </div>\r\n"
		+ "                    </div>\r\n"
		+ "                </div>\r\n"
		+ "                <div class=\"btn-container flex w-full items-center mr-0 justify-end\">\r\n"
		+ "                    <button\r\n"
		+ "                        class=\"contact-form-btn outline-none border-none bg-black py-2 px-4 text-white hover:bg-border-color hover:text-black hover:cursor-pointer\"\r\n"
		+ "                        type=\"submit\" id=\"send-button\" onclick=\"sendinfo();\">\r\n"
		+ "                        SEND\r\n"
		+ "                    </button>\r\n"
		+ "                </div>\r\n"
		+ "            </div>\r\n"
		+ "        </div>\r\n"
		+ "        <img src=\"/HelloWorld/TheBand/assest/img/map.jpg\" alt=\"\"\r\n"
		+ "            class=\"location-map w-full align-middle grayscale-50\" />\r\n"
		+ "    </div>\r\n"
		+ "    <footer\r\n"
		+ "        class=\"footer-container py-16 px-4 max-w-3xl w-full flex ml-auto mr-auto items-center justify-between flex-col\">\r\n"
		+ "        <div>\r\n"
		+ "            <a class=\"text-2xl text-black hover:opacity-70 hover:cursor-pointer\" target=\"_blank\"\r\n"
		+ "                rel=\"noopener noreferrer\" href=\"https://facebook.com\">\r\n"
		+ "                <i class=\"mx-2.5 fa-brands fa-facebook\" style=\"color: #3b5998\"></i>\r\n"
		+ "            </a>\r\n"
		+ "            <a class=\"text-2xl text-black hover:opacity-70 hover:cursor-pointer\" target=\"_blank\"\r\n"
		+ "                rel=\"noopener noreferrer\" href=\"https://instagram.com\">\r\n"
		+ "                <i class=\"mx-2.5 fa-brands fa-instagram\" style=\"color: #e4405f\"></i>\r\n"
		+ "            </a>\r\n"
		+ "            <a class=\"text-2xl text-black hover:opacity-70 hover:cursor-pointer\" target=\"_blank\"\r\n"
		+ "                rel=\"noopener noreferrer\" href=\"https://snapchat.com\">\r\n"
		+ "                <i class=\"mx-2.5 fa-brands fa-snapchat\" style=\"color: #fffc00\"></i>\r\n"
		+ "            </a>\r\n"
		+ "            <a class=\"text-2xl text-black hover:opacity-70 hover:cursor-pointer\" target=\"_blank\"\r\n"
		+ "                rel=\"noopener noreferrer\" href=\"https://pinterest.com\">\r\n"
		+ "                <i class=\"mx-2.5 fa-brands fa-pinterest\" style=\"color: #e60023\"></i>\r\n"
		+ "            </a>\r\n"
		+ "            <a class=\"text-2xl text-black hover:opacity-70 hover:cursor-pointer\" target=\"_blank\"\r\n"
		+ "                rel=\"noopener noreferrer\" href=\"https://twitter.com\">\r\n"
		+ "                <i class=\"mx-2.5 fa-brands fa-x-twitter\" style=\"color: #1da1f2\"></i>\r\n"
		+ "            </a>\r\n"
		+ "            <a class=\"text-2xl text-black hover:opacity-70 hover:cursor-pointer\" target=\"_blank\"\r\n"
		+ "                rel=\"noopener noreferrer\" href=\"https://linkedin.com\">\r\n"
		+ "                <i class=\"mx-2.5 fa-brands fa-linkedin\" style=\"color: #0077b5\"></i>\r\n"
		+ "            </a>\r\n"
		+ "            <p class=\"footer-message my-4 w-full text-center\">\r\n"
		+ "                Powered by\r\n"
		+ "                <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://youtube.com\"\r\n"
		+ "                    style=\"text-decoration: underline\">Youtube</a>\r\n"
		+ "            </p>\r\n"
		+ "        </div>\r\n"
		+ "    </footer>\r\n"
		+ "    <div id=\"ticketmodal\" class=\"ticketmodal hidden fixed top-0 bottom-0 w-full h-full pt-24 z-50 bg-color_overlay justify-center\">\r\n"
		+ "        <div class=\"modal-container relative opacity-1 flex max-w-4xl m-auto bg-white flex-col items-center justify-center shadow-custom\"\r\n"
		+ "            id=\"modal-container\">\r\n"
		+ "            <header class=\"ticket-page py-8 px-4 bg-greenish w-full text-center text-white\">\r\n"
		+ "                <h2 class=\"my-2.5 tracking-widest font-normal\">\r\n"
		+ "                    <i class=\"fa fa-suitcase w3-margin-right ml-4\"></i>Tickets\r\n"
		+ "                </h2>\r\n"
		+ "            </header>\r\n"
		+ "            <div class=\"modal-content flex flex-col w-full items-center justify-center px-4\">\r\n"
		+ "                <p class=\"title my-4 mr-auto\">\r\n"
		+ "                    <i class=\"fa fa-shopping-cart\"></i> Tickets, $15 per person\r\n"
		+ "                </p>\r\n"
		+ "                <input type=\"text\" class=\"modal-input p-2 border border-hover-bg outline-yellow-300 w-full leading-5.5\"\r\n"
		+ "                    placeholder=\"How many?\" required name=\"Number\" />\r\n"
		+ "                <p class=\"title my-4 mr-auto\"><i class=\"fa fa-user\"></i> Send to?</p>\r\n"
		+ "                <input type=\"text\" class=\"modal-input p-2 border border-hover-bg outline-yellow-300+ w-full leading-5.5\"\r\n"
		+ "                    placeholder=\"Where to?\" required name=\"text\"  />\r\n"
		+ "                <button\r\n"
		+ "                    class=\"modal-pay-btn p-4 my-4 bg-greenish w-full outline-none border-none text-white font-medium hover:bg-hover-bg hover:text-black hover:cursor-pointer\"\r\n"
		+ "                    type=\"submit\">\r\n"
		+ "                    PAY\r\n"
		+ "                </button>\r\n"
		+ "                <div class=\"this-container w-full inline-flex items-center justify-between my-4\">\r\n"
		+ "                    <button\r\n"
		+ "                        class=\"modal-close-btn flex items-center py-2 px-4 bg-red-500 text-white outline-none border-none leading-5.5 align-middle hover:bg-hover-bg hover:text-black hover:cursor-pointer\"\r\n"
		+ "                        onclick=\"closeModal();\">\r\n"
		+ "                        Close <i class=\"fa fa-remove font-bold mt-1 ml-0.5\"></i>\r\n"
		+ "                    </button>\r\n"
		+ "                    <p class=\"\">\r\n"
		+ "                        Need <a href=\"\" class=\"text-blue-700 underline\">help?</a>\r\n"
		+ "                    </p>\r\n"
		+ "                </div>\r\n"
		+ "            </div>\r\n"
		+ "        </div>\r\n"
		+ "    </div>\r\n"
		+ "    <div\r\n"
		+ "        class=\"fixed bottom-5 right-5 cursor-pointer hover:bg-black hover:text-white text-gray-500 text-2xl py-2 px-2 bg-gray-300 rounded-3xl\">\r\n"
		+ "        <a href=\"#top\" class=\"ToTop\">\r\n"
		+ "            <i class=\"fa-solid fa-arrow-up\"></i>\r\n"
		+ "        </a>\r\n"
		+ "    </div>\r\n"
		+ "</body>\r\n"
		+ "<script src=\"/HelloWorld/TheBand/javascript/base.js\"></script>\r\n"
		+ "\r\n"
		+ "</html>");
}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
		

	}

}
